version: '3.8'
services:
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
